### ISSUE TITLE
Tese em Latex?

### ISSUE THREAD

**Issue by vitorcalistosilva** [jose-a-sa/fcup-thesis#1]
Olá. Desculpa usar este meio para colocar esta questão.

Apenas adaptaste a "title page" e a "booklet cover" ou todo o layout da tese?

Estou a perguntar porque tenho interesse em fazer toda a tese em LaTex e dava jeito saber se alguém já fez isso.

Obrigado.

**Comment by jose-a-sa** [comment]
Olá Vitor,

Este projeto Latex apenas gera a titlepage, booklet, cd+cover. Se quiseres incluir a titlepage na tua tese recomendo que clones este repositorio, convertas o main.tex em pdf usando as instruções do README.md e uses o command `\includepdf[page={1},pagecommand={},scale=1]{main.pdf}` na tua tese latex para incluires certas paginas.

Relavivamente ao layout da tese eu utilizei o modelo no meu outro repositorio: [@jose-a-sa/thesis-physics](https://github.com/jose-a-sa/thesis-physics). O layout da tese nao e assim tao restrito como está definido na pagina da FCUP. Desde que tenha um espaçamento e tamanho de letra aceitável, não há problema em ser aceite.

Aqui tens um exemplo de como podes modificar o `main.tex` no `thesis-physics` depois de clonares este repositorio para dentro de uma pasta (neste caso chamada `Cover`) e gerares o pdf:
```
%-----------------------------------------------------------------------------------
%	DOCUMENT
%-----------------------------------------------------------------------------------

\begin{document}

\pagestyle{empty}
\setcounter{page}{0}
\includepdf[page={1},pagecommand={},scale=1]{Cover/main.pdf}
\cleardoublepage
\pagestyle{fancy}

%-----------------------------------------------------------------------------------
%	TITLE PAGE
%-----------------------------------------------------------------------------------
```

PS: é importante que uses `\cleardoublepage` para fazer os pagebreaks correctamente caso estejas a usar as flags `twoside` (estilo livro) ou `oneside` (normal).

**Comment by vitorcalistosilva** [comment]
Obrigado. 

Por caso ainda não sabia, estou a começar agora a usar latex um pouco mais a sério, aquilo que sugeriste no primeiro parágrafo.

Vou fazer o que recomendas. Já ajudou bastante. Obrigado.
