### ISSUE TITLE
Contents

### ISSUE THREAD

**Issue by FRibeiro98** [jose-a-sa/fcup-thesis#2]
Olá José. 
Há alguma maneira de remover o Abstract e os Acknowledges dos Contents. 
Obrigado.

**Comment by jose-a-sa** [comment]
Neste repositório apenas tem um projecto em LaTeX para gerar as capas necessárias automaticamente segundo o layout especificado pela FCUP. Não tem Abstract ou Acknowledgements neste projecto. Se tiveres a referir-te ao repositório [thesis-physics](https://github.com/jose-a-sa/thesis-physics), cria um issue nesse repo.

**Comment by jose-a-sa** [comment]
@FRibeiro98 
PS: se o objectivo for um fix rápido para Abstract ou Acknowledgements não aparecer no TOC (mas continuar a incluir essa páginas no documento), é necessário comentar as linhas de [Thesis.cls](https://github.com/jose-a-sa/thesis-physics/blob/master/Thesis.cls) que começam com `\addtotoc` nos ambientes para o Abstract e Acknowledgements:

- Linhas 429-434
```TeX
\newenvironment{abstract}[1][]
{%
  \setkeys{absenv}{#1}%
  \btypeout{\@abstitle}%
  \addtotoc{\@abstitle}%
  \thispagestyle{plain}%
```
- Linhas 645-649:
```TeX
\newenvironment{acknowledgements}
{%
  \btypeout{\acknowledgementsname}
  \addtotoc{\acknowledgementsname}
  \pagestyle{empty}
```

**Comment by FRibeiro98** [comment]
Era precisamente isso. Resolvido ! Obrigado José
